image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test 

before_script:
  - 'cd SmartGarage'
  - 'dotnet restore'
  - 'dotnet --info'
  
build:
  stage: build
  script:
    - 'dotnet build --no-restore' 

tests:
  stage: test
  script:
    - 'dotnet test --no-restore'
